// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/add-to-shopping-cart": {
    params: {};
  };
  "/catalog": {
    params: {};
  };
  "/tree/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/add-to-shopping-cart" | "/catalog" | "/tree/:id";
  };
  "pages/home/home.tsx": {
    id: "pages/home/home";
    page: "/";
  };
  "pages/addToShoppingCart.tsx": {
    id: "pages/addToShoppingCart";
    page: "/add-to-shopping-cart";
  };
  "pages/catalog/catalog.tsx": {
    id: "pages/catalog/catalog";
    page: "/catalog";
  };
  "pages/tree/tree.tsx": {
    id: "pages/tree/tree";
    page: "/tree/:id";
  };
};